name: Build & Deploy Image to Cloud Run and Deploy DAGs to GCP Bucket

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GOOGLE_PROJECT }}
  REPOSITORY_NAME: transformations-repository
  IMAGE_NAME: dbt-transformations
  GCP_REGION: europe-west9

jobs:
  # common-steps:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       id: checkout
  #       uses: actions/checkout@v3

  #     - name: Authentification
  #       id: auth
  #       uses: google-github-actions/auth@v1
  #       with:
  #         credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

  #     - name: Setup Google Cloud SDK
  #       id: setup-gcloud
  #       uses: google-github-actions/setup-gcloud@v1
  #       with:
  #         project_id: ${{ secrets.GOOGLE_PROJECT }}

  build-push:
    #needs: common-steps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v3

      - name: Authentification
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Setup Google Cloud SDK
        id: setup-gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}

      - name: Create Artifact Registry Repository
        run: |
          gcloud artifacts repositories create $REPOSITORY_NAME \
            --repository-format=docker \
            --location=$GCP_REGION \
            --description="Docker repository for transformations" \
            --project=$PROJECT_ID || echo "Repository already exists"

      - name: Configure Docker Client
        run: gcloud auth configure-docker $GCP_REGION-docker.pkg.dev --quiet

      - name: Build and Push Docker Image to GCP Artifact Registry
        run: |
          gcloud builds submit --tag $GCP_REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$IMAGE_NAME:${GITHUB_SHA::7}
      
      - name: Add Latest Tag to Docker Image
        run: |
          gcloud container images add-tag $GCP_REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$IMAGE_NAME:${GITHUB_SHA::7} $GCP_REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$IMAGE_NAME:latest
      
      # 'dbt-transformations-00001-t8h' is not ready and cannot serve traffic.
      - name: Deploy to Cloud Run
        run: |
          gcloud run jobs deploy $IMAGE_NAME \
            --image $GCP_REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$IMAGE_NAME:latest \
            --region $GCP_REGION \
            --platform managed \
            --allow-unauthenticated \
            --max-retries 3 \
            --task-timeout=300s    

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v3

      - name: Authentification
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Setup Google Cloud SDK
        id: setup-gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}

      - name: Upload DAGs to GCP Bucket
        run: |
          gsutil -m cp -r dags/* gs://$GCP_REGION-dev-composer-e-aeaa3dd5-bucket/dags