name: Build & Deploy Image to Cloud Run and Deploy DAGs to GCP Bucket  

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GOOGLE_PROJECT }}
  REPOSITORY_NAME: transformations-repository
  IMAGE_NAME: dbt-transformations
  GCP_REGION: europe-west9

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authentification
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker Client
        run: gcloud auth configure-docker $GCP_REGION-docker.pkg.dev --quiet

      - name: Build and Push Docker Image to GCP Artifact Registry
        run: |
          gcloud builds submit --tag $GCP_REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$IMAGE_NAME:${GITHUB_SHA::7}
          gcloud container images add-tag $GCP_REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$IMAGE_NAME:${GITHUB_SHA::7} $GCP_REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$IMAGE_NAME:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $IMAGE_NAME \
            --image $GCP_REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$IMAGE_NAME:latest \
            --region $GCP_REGION \
            --platform managed \
            --allow-unauthenticated

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authentification
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Setup Google Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}

      - name: Upload DAGs to GCP Bucket
        run: |
          gsutil -m cp -r dags/* gs://europe-west9-dev-composer-e-aeaa3dd5-bucket/dags